sgpa/apps/urls.py
from django.conf.urls import patterns, url
from django.conf.urls.static import static
from django.conf import settings

from apps import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    
    url(r'^ingresar/$', views.ingresar, name='ingresar'),
    url(r'^inicio/(?P<user_id>\d+)/(?P<role_id>\d+)/$', views.inicio, name='inicio'),        
    url(r'^ingresar/recuperarContrasena/$', views.recuperarContrasena, name='recuperar_contrasena'),
    url(r'^user_private_admin/$', views.privado, name='user_private_admin'),
    url(r'^user_private_user/$', views.privadoNoadmin, name='privadoNoadmin'),
    url(r'^cerrar/$', views.cerrar, name='cerrar'),
    #url(r'^modadmin/$', views.modadmin.as_view(), name='modadmin'),
    
    url(r'^(?P<user_logged>\d+)/modadmin/$', views.adminmod, name='adminmod'),
    url(r'^(?P<user_logged>\d+)/modadmin/adminuser/$', views.listuser, name="listuser"),
    url(r'^(?P<user_logged>\d+)/modadmin/adminuser/nuevo', views.nuevo_usuario, name='nuevo_usuario'),
    url(r'^(?P<user_logged>\d+)/modadmin/adminuser/(?P<user_id>\d+)/modificaruser/$', views.muser, name="muser"),
    url(r'^(?P<user_logged>\d+)/modadmin/adminuser/(?P<user_id>\d+)/eliminaruser/$', views.deluser, name="deluser"),
    
    url(r'^(?P<user_logged>\d+)/modadmin/adminrole/$', views.listrolesmod, name="listrolesmod"),
    url(r'^(?P<user_logged>\d+)/modadmin/adminrole/crearrole/$', views.listpermisos, name="listpermisos"),
    url(r'^(?P<user_logged>\d+)/modadmin/adminrole/(?P<role_id>\d+)/modificarrol/$', views.rolemodify, name="rolemodify"),
    url(r'^(?P<user_logged>\d+)/modadmin/adminrole/(?P<role_id>\d+)/(?P<proyecto_id>\d+)/modificarrol/rolesetp$', views.rolemodifypermisos, name="rolemodifypermisos"),
    url(r'^(?P<user_logged>\d+)/modadmin/adminrole/(?P<role_id>\d+)/(?P<proyecto_id>\d+)/modificarrol/rolesetp/asignarpermisosmod/$', views.asignarpermisosmod, name="asignarpermisosmod"),
    url(r'^(?P<user_logged>\d+)/modadmin/adminrole/(?P<role_id>\d+)/eliminarrole/$', views.roledelete, name="roledelete"),
    url(r'^(?P<user_logged>\d+)/modadmin/adminrole/(?P<role_id>\d+)/asignarrol/$', views.asignarrol, name="asignarrol"),
    
    url(r'^(?P<user_logged>\d+)/modadmin/adminproyecto/$', views.adminproject, name="adminproject"),
    url(r'^(?P<user_logged>\d+)/modadmin/adminproyecto/crearproyecto/$', views.crearProyecto, name="crearProyecto"),
    url(r'^(?P<user_logged>\d+)/modadmin/adminproyecto/verproyectos/$', views.verProyectos, name="verProyectos"),
    url(r'^(?P<user_logged>\d+)/modadmin/adminproyecto/verproyectosporusuario/$', views.verprojusuario, name="verprojusuario"),
    url(r'^(?P<user_logged>\d+)/modadmin/adminproyecto/crearproyecto/(?P<proyecto_pk>\d+)/agregarPlantilla/$', views.agregarPlantilla, name='agregarPlantilla'),
    
    url(r'^(?P<user_logged>\d+)/modadmin/adminflujo/$', views.listflowmod, name="listflowmod"),
    url(r'^(?P<user_logged>\d+)/modadmin/adminflujo/crearflujo/$', views.crearflujo, name="crearflujo"),
    url(r'^(?P<user_logged>\d+)/modadmin/adminflujo/crearflujo/(?P<flow_id>\d+)/setactividades/$', views.setactividades, name="setactividades"),
    url(r'^(?P<user_logged>\d+)/modadmin/adminflujo/(?P<flow_id>\d+)/modificarflujo/$', views.editarflujos, name="editarflujos"),
    url(r'^(?P<user_logged>\d+)/modadmin/adminflujo/(?P<flow_id>\d+)/modificarflujo/setactividades/$', views.listactivitiesmod, name="listactivitiesmod"),
    url(r'^(?P<user_logged>\d+)/modadmin/adminflujo/(?P<flow_id>\d+)/setactividadesmod/(?P<actv_id>\d+)/', views.setactividadesmod, name="setactividadesmod"),
    url(r'^(?P<user_logged>\d+)/modadmin/adminflujo/(?P<flow_id>\d+)/eliminarflujo/$', views.flowdelete, name="flowdelete"),
    url(r'^(?P<user_logged>\d+)/modadmin/adminflujo/(?P<flow_id>\d+)/setactividadesdel/(?P<actv_id>\d+)/', views.setactividadesdel, name="setactividadesdel"),
    
    
    #url(r'^modproyecto/$', views.modproyecto.as_view(), name='modproyecto'),
    url(r'^modproyecto/$', views.modproyecto.as_view(), name='modproyecto'),
    
    
    #url(r'^modadmin/adminuser/moduser/$', views.listuser, name='listuser'),    
   # url(r'^modadmin/adminuser/moduser/mod/$', views.moduser, name="moduser"),
   
    url(r'^(?P<usuario_id>\d+)/modproyecto/$', views.listproyectosdelusuario, name='listproyectosdelusuario'),
    url(r'^(?P<proyecto_id>\d+)/modproyecto/accionesproyecto$', views.accionesproyecto, name='accionesproyecto'),
    
    url(r'^(?P<proyecto_id>\d+)/modproyecto/accionesproyecto/projectDetalles$', views.projectDetalles, name='projectDetalles'),
    
    url(r'^(?P<proyecto_id>\d+)/modproyecto/accionesproyecto/adminsprint/(?P<sprint>\d+)/$', views.listsprint, name='listsprint'),
    url(r'^(?P<proyecto_id>\d+)/modproyecto/accionesproyecto/adminhu/$', views.listhu, name='listhu'),
    url(r'^(?P<proyecto_id>\d+)/modproyecto/accionesproyecto/adminhu/crearhu/$', views.crearHu, name='crearHu'),
    url(r'^(?P<proyecto_id>\d+)/modproyecto/accionesproyecto/adminhu/(?P<hu_id>\d+)/$', views.modificarHu, name="modificarHu"),
    url(r'^(?P<proyecto_id>\d+)/modproyecto/accionesproyecto/adminhu/(?P<hu_id>\d+)/principal/$', views.huprincipal, name="huprincipal"),
    url(r'^(?P<proyecto_id>\d+)/modproyecto/accionesproyecto/adminhu/(?P<hu_id>\d+)/log/$', views.hulog, name="hulog"),
    url(r'^(?P<proyecto_id>\d+)/modproyecto/accionesproyecto/adminhu/(?P<hu_id>\d+)/editar/$', views.editarHu, name="editarHu"),
    url(r'^(?P<proyecto_id>\d+)/modproyecto/accionesproyecto/adminhu/(?P<hu_id>\d+)/finalizarHu/$', views.finalizarHu, name="finalizarHu"),
    url(r'^(?P<proyecto_id>\d+)/modproyecto/accionesproyecto/adminhu/(?P<hu_id>\d+)/registro/$', views.registroHu, name="registroHu"),
    url(r'^(?P<proyecto_id>\d+)/modproyecto/accionesproyecto/adminhu/(?P<hu_id>\d+)/registro/nuevo/$', views.crearregistroHu, name="crearregistroHu"),
    url(r'^(?P<proyecto_id>\d+)/modproyecto/accionesproyecto/adminhu/(?P<hu_reg_id>\d+)/registro/ver/$', views.verregistroHu, name="verregistroHu"),
    url(r'^(?P<proyecto_id>\d+)/modproyecto/accionesproyecto/adminhu/(?P<hu_id>\d+)/eliminar/$', views.eliminarHu, name="eliminarHu"),
    url(r'^(?P<proyecto_id>\d+)/modproyecto/accionesproyecto/adminhu/(?P<hu_id>\d+)/setflujo/$', views.listhuflujo, name='listhuflujo'),
    url(r'^(?P<proyecto_id>\d+)/modproyecto/accionesproyecto/adminhu/(?P<hu_id>\d+)/asignarflujo/$', views.asignarflujoHu, name='asignarflujoHu'),
    url(r'^(?P<proyecto_id>\d+)/modproyecto/accionesproyecto/adminhu/(?P<hu_id>\d+)/setestado/$', views.setEstadoHu, name='setEstadoHu'),
    url(r'^(?P<proyecto_id>\d+)/modproyecto/accionesproyecto/adminhu/(?P<hu_id>\d+)/versiones/$', views.listhuversiones, name='listhuversiones'),
    url(r'^(?P<proyecto_id>\d+)/modproyecto/accionesproyecto/adminhu/(?P<hu_id>\d+)/versiones/(?P<huv_id>\d+)/cambios/$', views.huvcambios, name='huvcambios'),
    url(r'^(?P<proyecto_id>\d+)/modproyecto/accionesproyecto/adminhu/(?P<hu_id>\d+)/versiones/(?P<huv_id>\d+)/volverversion/$', views.volverVersionHU, name='volverVersionHU'),
    url(r'^(?P<proyecto_id>\d+)/modproyecto/accionesproyecto/adminhu/(?P<hu_id>\d+)/resumen/$', views.resumenHu, name='resumenHu'),
    url(r'^(?P<proyecto_id>\d+)/modproyecto/accionesproyecto/adminhu/(?P<hu_id>\d+)/fileManager/$', views.fileAdjunto, name='fileAdjunto'),

    url(r'^(?P<proyecto_id>\d+)/modproyecto/accionesproyecto/adminhu/(?P<hu_id>\d+)/fileManager/versiones/$', views.versionesAdjunto, name='versionesAdjunto'),

    url(r'^(?P<proyecto_id>\d+)/modproyecto/accionesproyecto/adminhu/(?P<hu_id>\d+)/agregarnota/$', views.agregarNotaHu, name='agregarNotaHu'),
    url(r'^(?P<proyecto_id>\d+)/modproyecto/accionesproyecto/adminhu/(?P<hu_id>\d+)/notas/$', views.notasHu, name='notasHu'),

    url(r'^modproyecto/accionesproyecto/adminhu/(?P<f_id>\d+)/fileManager/descarga/$', views.send_file, name='send_file'),
    url(r'^(?P<proyecto_id>\d+)/(?P<hu_id>\d+)/modproyecto/accionesproyecto/adminhu/(?P<f_id>\d+)/fileManager/eliminar/$', views.delete_file, name='delete_file'),
    
    url(r'^(?P<proyecto_id>\d+)/modproyecto/accionesproyecto/asigparticipante$', views.listasigparticipante, name='listasigparticipante'),
    url(r'^(?P<proyecto_id>\d+)/(?P<usuario_id>\d+)/modproyecto/accionesproyecto/listasigparticipanterol$', views.listasigparticipanterol, name='listasigparticipanterol'),
    url(r'^(?P<proyecto_id>\d+)/(?P<usuario_id>\d+)/modproyecto/accionesproyecto/asigparticipanterol$', views.asigparticipanterol, name='asigparticipanterol'),
    url(r'^(?P<proyecto_id>\d+)/modproyecto/accionesproyecto/listelimparticipante$', views.listelimparticipante, name='listelimparticipante'),
    url(r'^(?P<proyecto_id>\d+)/(?P<usuario_id>\d+)/modproyecto/accionesproyecto/elimparticipante$', views.elimparticipante, name='elimparticipante'),
    url(r'^(?P<proyecto_id>\d+)/modproyecto/accionesproyecto/listflujosproyectos$', views.listflujosproyectos, name='listflujosproyectos'),
    url(r'^(?P<proyecto_id>\d+)/modproyecto/accionesproyecto/listflujosproyectos/agregarPlantillaProyecto$', views.agregarPlantillaProyecto, name='agregarPlantillaProyecto'),
    url(r'^(?P<proyecto_id>\d+)/modproyecto/accionesproyecto/listflujosproyectos/agregarPlantillaProyectoMod$', views.listflujosproyectosMod, name='listflujosproyectosMod'),
    url(r'^(?P<proyecto_id>\d+)/(?P<flujo_id>\d+)/modproyecto/accionesproyecto/listflujosproyectos/eliminarplantillaProyecto$', views.flowdeleteproj, name='flowdeleteproj'),
    url(r'^(?P<proyecto_id>\d+)/(?P<flujo_id>\d+)/(?P<actividad_id>\d+)/modproyecto/accionesproyecto/listflujosproyectos/modificarFlujoProyectoMod$', views.flujosproyectosRequestMod, name='flujosproyectosRequestMod'),
    url(r'^(?P<proyecto_id>\d+)/(?P<flujo_id>\d+)/(?P<actividad_id>\d+)/modproyecto/accionesproyecto/listflujosproyectos/modificarFlujoProyectoModAct$', views.flujosproyectosRequestModAct, name='flujosproyectosRequestModAct'),

sgpa/sgpa/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^apps/', include('apps.urls', namespace="apps")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^usuario/', include('apps.urls')),
    url(r'^privado/', include('apps.urls')),
    url(r'^privadoNoadmin/', include('apps.urls')),
    url(r'^cerrar/', include('apps.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sgpa/apps/templates/apps/flow_activitie_eliminated.html
{% extends 'base.html' %}
{% block titulo %}
<h1>Administrar Flujos</h1>
{% endblock %}
{% block encabezado %}
<h1>{{flow_descripcion}}</h1>
{% endblock %}
{% block contenido %}
<h1>Actividad eliminada</h1>

<a href="{% url 'apps:listactivitiesmod' flow_id %}">Volver a Administracion</a>
{% endblock %}
{% block atras %}
<a href="{% url 'apps:listactivitiesmod' flow_id %}">Atras</a>
{% endblock %}

sgpa/apps/templates/apps/flow_create.html
{% extends 'base.html' %}
{% block titulo %}
<h1>Administrar Flujos</h1>
{% endblock %}
{% block encabezado %}
<h1>Nuevo Flujo</h1>
{% endblock %}
{% block contenido %}
{% if error %}
	<table border=1 bordercolor="red" width=100%>
		<tr><td align="center"><font color="red"><p>El nombre que eligio ya esta siendo utilizado. Por favor, elija otro.</p></font></td></tr>
	</table>
<br>
{% endif %}
<form action="{% url 'apps:crearflujo' user_logged %}" method='post'>{% csrf_token %}
	<table>{{ form }}</table>
	<input type="submit" value="Registrar">
</form>
{% endblock %}
{% block atras %}
<a href="{% url 'apps:listflowmod' user_logged %}">Atras</a>
{% endblock %}

sgpa/apps/templates/apps/hu_flow_set.html
{% extends 'base.html' %}

{% block contenido %}
<h3>Flujo Asignado Correctamente</h3>
<br>
<a href="{% url 'apps:listhu' proyecto_id %}">Volver</a>
{% endblock %}
{% block atras %}
<a href="{% url 'apps:listhu' proyecto_id %}">Volver</a>
{% endblock %}

sgpa/apps/templates/apps/hu_registro_mostrar.html
{% extends 'base.html' %}
{% block uptitulo %}
	<h1>{{proyecto.nombre}}</h1>
{% endblock %}
{% block titulo %}
	<table>
		<tr>
		
			<td width=125px><h2><font color="#686868">{{hu.codigo}}</font></h2></td>
			<td ><h2>{{hu.nombre}}</h2></td>
		</tr>
	</table>
{% endblock %}
{% block index %}
	
	<li>
		<a href="{% url 'apps:accionesproyecto' proyecto.id %}"><i class="fa fa-fw fa-edit"></i>{{proyecto.nombre}}</a>
	</li>
	
		<li>
              <a href="{% url 'apps:huprincipal' proyecto.id hu.id %}"></i><font color="FFFFFF">{{hu.codigo}} {{hu.nombre}}</font></a>          
        </li>	
	
{% endblock %}

{% block contenido %}
	<legend><font color="888888">Registro de Actividades</font></legend>

	<table border=0px bordercolor="green" width=100%>
		
		<tr>
			<td width=20%><b>Tarea:</b></td>
			<td>{{hu_reg.descripcion_tarea}}</td></tr>
			<tr><td><b>Horas Registradas:</b></td>
			<td>{{hu_reg.tiempo_Real}}</td></tr>
	</table>
	<br>
	<table border=0px bordercolor="green" width=100%>
	
			<tr><td width = 20%><b>Sprint:</b></td>
			{% if hu_reg.sprint == 0 %}
				<td>No asignado</td>
			{% else %}
				<td>{{hu_reg.sprint}}</td>
			{% endif %}
			</tr>
			<tr><td><b>Flujo:</b></td><td>{{flujo}}</td></tr>
			<tr><td><b>Actividad en Flujo:</b></td><td>{{actividad}}</td></tr>
			<tr><td><b>Estado en Actividad:</b></td><td>{{estado}}</td></tr>
		
	
	</table>
	
{% endblock %}
{% block atras %}
	<a href="{% url 'apps:registroHu' proyecto.id hu_reg.idr  %}">Volver</a>
{% endblock %}

sgpa/apps/templates/apps/project_acciones.html
{% extends 'base_proj.html' %}
{% block titulo %}
	<b>{{proyecto.nombre}}</b>
{% endblock %}

{% block script %}
	
 
{% endblock %}
{% block index %}
	<li>
		<a href="{% url 'apps:accionesproyecto' proyecto.id %}"><i class="fa fa-fw fa-edit"></i>{{proyecto.nombre}}</a>
	</li>


		
	{%if misPermisos.PS == True or misPermisos.VP == True %}
	<li>
		<a href="{% url 'apps:sprints' proyecto.id 0 0 %}"><i class="fa fa-ful fa-edit"></i>Sprints</a>
	</li>
	{% endif %}
	
	{% if misPermisos.CUS or misPermisos.MUS or misPermisos.EUS %}
	<li>
		<a href="{% url 'apps:listhu' proyecto.id %}"><i class="fa fa-fw fa-edit"></i>Product Backlog</a>
	</li>	
	{% endif %}
	<!-- 
	{% if misPermisos.PS %}

	<li>
		<a href="{% url 'apps:listsprint' proyecto.id 0 %}"><i class="fa fa-fw fa-edit"></i>Sprint Backlog</a>
	</li>	

		
	{% endif %}
	 
	 -->
	
	{% if misPermisos.CRP or misPermisos.ERP or misPermisos.MRP %}

	<li>
		<a href="{% url 'apps:listrolesproj' proyecto.id %}"><i class="fa fa-fw fa-edit"></i>Roles</a>
	</li>

	
	{% endif %}
		
	{% if misPermisos.AFP %}
		<li>
			<a href="{% url 'apps:listflujosproyectosMod' proyecto.id %}"><i class="fa fa-fw fa-edit"></i>Flujos</a>
		</li>
	{% endif %}
	

	{%if misPermisos.VP %}
	<li>
		<a href="{% url 'apps:verCliente' proyecto.id%}"><i class="fa fa-fw fa-edit"></i>Ver cliente</a>
	</li>
	{% endif %}
	
	{% if misPermisos.VP %}
	<li>
		<a href="{% url 'apps:reportes' proyecto.id %}"><i class="fa fa-fw fa-edit"></i>Reportes</a>
	</li>
	{% endif %}
	
	{% if misPermisos.VP %}
		<li>
			<a href="{% url 'apps:projectDetalles' proyecto.id %}"><i class="fa fa-fw fa-edit"></i>Detalles del Proyecto</a>
		</li>
	{% endif %}	
	
{% endblock %}

{% block encabezado %}

{% endblock %}


{% block contenido %}
	{% if mensaje %}
		<table border=1 bordercolor="green" width=100%>
			<tr><td align="center"><font color="green"><p>{{mensaje}}</p></font></td></tr>
		</table>
	{% endif %}
	{% if mensaje_error %}
		<table border=1 bordercolor="red" width=100%>
			<tr><td align="center"><font color="red"><p>{{mensaje_error}}</p></font></td></tr>
		</table>
	{% endif %}
{% if proyecto.nro_sprint != 0 %}
	<h1>Sprint {{proyecto.nro_sprint}}</h1>
{% endif %}
<br>
<table  border=0px  frame="lhs" cellspacing=1 cellpadding=20 width=100%>	
	<center>

	{% for f in flujo %}
		
		<tr>
			<td>
				<table bgcolor="#C0C0C0" bordercolor="#888888 " border=1px cellspacing=1 cellpadding=20 width=100%>
					<tr>
						<strong>{{f.descripcion}}</strong>
					</tr>
				</center>
					<tr height=30>
						{% for actividad in actividades %}
							{% if actividad.flujo_id == f.id%}
								<td  bgcolor="#282828 " colspan="3" align="center"  width=200 height=50><font color="#FFFFFF" style="text-transform: uppercase;">{{actividad.descripcion}}</font></td>
							
							{% endif %}
						{% endfor %} 
					<tr>		
				
					<tr>
						{% for actividad in actividades %}
					 		{% if actividad.flujo_id == f.id%}
								 <td width=65  bgcolor="#D0D0D0  " >To Do </td><td  bgcolor="#D0D0D0 "  width=65>Doing</td><td  bgcolor="#D0D0D0 "  width=65>Done</td>
							{% endif %}
						{% endfor %} 
					</tr>


					
					
					{% if hus %}
					{% for h in hus %}
						{% if h.f_actividad != 0 %}
							<tr>
								{% for i in tamanolista %}
								
									{% if  h.flujo == f.id and forloop.counter <= f.tamano %}
										{% if forloop.counter == h.flujo_posicion  %}
											<!-- <td><a href="{% url 'apps:setEstadoHu' proyecto.id h.id %}">{{h.nombre}}</a></td> -->
											{% if scrum or user_logged.id == h.usuario_Asignado %}
										 		<td  bgcolor="#F0F0F0"  height=100 valign="top" border=10px>
										 			{% if h.estado_scrum.id == 5 %}<!-- Finalizado -->
											 			<big><font title="Finalizado" color="#0000F0"><i class="fa fa-fw fa-check-circle"></i></font></big>
											 			<small><a href="{% url 'apps:huprincipal' proyecto.id h.id %}"><font color="#0000"><b>{{h.nombre}}</b></font></a></small>
											 		{% elif h.estado_scrum.id == 6 %}<!-- Cancelado -->
											 			<big><font title="Cancelado" color="#FF0000"><i class="fa fa-fw fa-times-circle"></i></font></big>
											 			<small><a href="{% url 'apps:huprincipal' proyecto.id h.id %}"><font color="#0000"><b>{{h.nombre}}</b></font></a></small>
											 		{% elif h.flujo_posicion == 1 %}
											 			<big><font title="Por Iniciar" color="#EE82EE"><i class="fa fa-fw fa-minus-circle"></i></font></big>
											 			<small><a href="{% url 'apps:huprincipal' proyecto.id h.id %}"><font color="#0000"><b>{{h.nombre}}</b></font></a></small>
													{% elif h.flujo_posicion > 1 and h.finalizado == False %}
											 			<big><font title="En progreso" color="#008000"><i class="fa fa-fw fa-arrow-circle-right"></i></font></big>
											 			<small><a href="{% url 'apps:huprincipal' proyecto.id h.id %}"><font color="#0000"><b>{{h.nombre}}</b></font></a></small>
											 		{% elif h.finalizado %}<!-- En espera -->
											 			<big><font title="En Revision" color="#FFA500"><i class="fa fa-fw fa-exclamation-circle"></i></font></big>
											 			<small><a href="{% url 'apps:huprincipal' proyecto.id h.id %}"><font color="#0000"><b>{{h.nombre}}</b></font></a></small>

											 		{% endif %}
										 			<table>
										 			<tr height=50px></tr>
										 			<tr>
										 				{% if user_logged.id == h.usuario_Asignado %}
											 				<td>
											 					<a href="{% url 'apps:setEstadoHu' proyecto.id h.id  %}"><font title="Cambiar Estado" color="#0000"><i class="fa fa-fw fa-calendar"></i></font></a>
											 				</td>
										 				{% endif %}
										 				{% if user_logged.id == h.usuario_Asignado %}
											 				<td>
											 					<a href="{% url 'apps:registroHu' proyecto.id h.id  %}"><font title="Registrar Horas" color="#0000"><i class="fa fa-fw fa-tasks"></i></font></a>
											 				</td>
										 				{% endif %}
										 				<td>
										 					<a href="{% url 'apps:notasHu' proyecto.id h.id %}"><font title="Agregar Notas" color="#0000"><i class="fa fa-fw fa-tablet"></i></font></a>
										 				</td>
										 			</tr>
										 			</table>
					
										 		</td>
										 	{% else %}
										 		<td  bgcolor="#F0F0F0"  height=100 valign="top" border=10px><small><font color="#0000"><b>{{h.nombre}}</b></font><font title="Agregar Notas" color="#0000"><i class="fa fa-fw fa-tablet"></i></font></small>
										 		</td>
										 	{% endif %}
										{% else %}
											<td height=100 ></td>
										{% endif %}
									{% endif %}
								{% endfor %}
							<tr>
						{% endif %}
					{% endfor %}
					{% else %}
						
					{% endif %}
				
				</table>
			</td>
		</tr>
	{% endfor %} 
	
</table>

	{% if proyecto.estado_id == 1 and scrum%}
		<form action="{% url 'apps:finalizarProyecto' proyecto.id 0 %}" method="post">{% csrf_token %}
			<br /><input type="submit", name="cambio", value="Finalizar Proyecto"><br />
		</form>
	{% endif %}

{% endblock %}

{% block equipo %}
	{% if misPermisos.APP or misPermisos.EPP %}
		<table height=1> 
			<tr><td><h4>Participantes:</h4></td>
			{% if proyecto.estado_id != 5 %}
				{% if misPermisos.APP %}
					<td><font color="#008000"><i class="fa fa-fw fa-plus"></i></font><a href="{% url 'apps:listasigparticipante' proyecto.id %}">Agregar</a></td>
				{% endif %}
				{% if misPermisos.EPP %}
					<td><font color="#FF0000"><i class="fa fa-fw fa-close"></i></font><a href="{% url 'apps:listelimparticipante' proyecto.id %}">Eliminar</a></td></tr>
				{% endif %}
			{% endif %}
		</table>
	{% endif %}
	<table width=100%	 height=100>
		<td width=66%>
			<table border=1px width=100%>
				<tr>
					<td><b>Usuario</b></td><td><b>Roles</b></td>
				</tr>
				{% if users %}
					{% for us in users %}
						{% if us.is_active == True %}
							<tr>
								<td><a href="{% url 'apps:verUser' proyecto.id us.id %}">{{us.username}}</a></td>
								<td>
									{% for eq in equipo %}
										{% if eq.usuario_id == us.id %}
											{% for ro in roles %}
												{% if eq.rol_id == ro.id and eq.usuario_id == us.id %}
													{{ro.descripcion}}.
												{% endif %}
											{% endfor %}
										{% endif %}
									{% endfor %}  
								</td>
							</tr>
						{% endif %}
					{% endfor %}
				{% endif %}
			</table>
		</td>
		<td width = 33%>
			<table border=1px width=100%>
				<tr><td><b>Ultima Conexion</b></td></tr>
				{% if users %}
					{% for us in users %}
						{% if us.is_active == True %}
							<tr><td>{{us.last_login}}</td></tr>
						{% endif %}		
					{% endfor %}
				{% endif %} 
			</table>
		</td>
	</table>
{% endblock %}
{% block atras %}
	<a href="{% url 'apps:listproyectosdelusuario' usuario.id %}">Volver</a>
{% endblock %}

sgpa/apps/templates/apps/user_delete.html
<h1>Eliminar Usuario</h1>